name: Speef click Game

on:
  push:
    branches: 
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Cheeckout Repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
            docker build \
            -t speed-clikc-game
      
      - name: Test Container
        run: |
            docker run \
              -p 8000:80
              --name test-containenr \
              speed-click-game
              
      - name: Stop container
        run: |
          docker stop test-container

